version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: school_erp_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/school_erp?schema=public
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=school_erp_production_secret_key_min32chars!!
      - PII_ENCRYPTION_KEY=school_erp_pii_encryption_key_32chars!!
      - STORAGE_PROVIDER=local
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - uploads_data:/app/public/uploads

  db:
    image: postgres:16-alpine
    container_name: school_erp_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=school_erp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  uploads_data:
